blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("communityapp.url")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

communityapp/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models.signals import post_save
from django.urls import reverse


class ProfileManager(models.Manager):
    def ExcludeAdminUser(self):
        qs = super(ProfileManager, self).all().exclude(user=1)
        return qs


class profile(models.Model):
    GENRE_CHOICES = (
        ('m', 'Male'),
        ('f', 'Female'),
    )
    MARITAL_STATUS_CHOICES = (
        ('s', 'Single'),
        ('m', 'Marride'),
        ('d', 'Divorced'),
        ('w', 'Widowed'),
    )

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    father_name = models.CharField(max_length=50, null=True, blank=True)
    birth_date = models.CharField(max_length=20, null=True, blank=True)
    genre = models.CharField(max_length=1, choices=GENRE_CHOICES, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    area = models.CharField(max_length=150, null=True, blank=True)
    city = models.CharField(max_length=15, null=True, blank=True)
    state = models.CharField(max_length=15, null=True, blank=True)
    country = models.CharField(max_length=15, null=True, blank=True)
    pincode = models.CharField(max_length=6, null=True, blank=True)
    phone = models.CharField(max_length=10, null=True, blank=True)
    email = models.CharField(max_length=150, null=True, blank=True)
    marital_status = models.CharField(max_length=1, choices=MARITAL_STATUS_CHOICES, null=True, blank=True)
    education = models.CharField(max_length=150, null=True, blank=True)
    education_detail = models.TextField(null=True, blank=True)
    occupation = models.CharField(max_length=150, null=True, blank=True)
    occupation_detail = models.TextField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False, auto_created=True)
    created = models.DateTimeField(auto_now=False, auto_now_add=True, auto_created=True)

    objects = ProfileManager()

    def __str__(self):
        return str(self.phone)

    def get_absolute_url(self):
        return reverse("profile:profile_detail", kwargs={"id": self.id})

    def get_update_url(self):
        return reverse("profile:profile_update", kwargs={"id": self.id})

    class Meta:
        ordering = ["id"]


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile.objects.create(user=instance, phone=instance.username)
    instance.profile.save()


post_save.connect(create_user_profile, sender=User)


class SubprofileManager(models.Manager):
    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.id
        qs = super(SubprofileManager, self).filter(content_type=content_type, object_id=obj_id)
        return qs


class SubProfile(models.Model):
    GENRE_CHOICES = (
        ('m', 'Male'),
        ('f', 'Female'),
    )
    MARITAL_STATUS_CHOICES = (
        ('s', 'Single'),
        ('m', 'Marride'),
        ('d', 'Divorced'),
        ('w', 'Widowed'),
    )

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    relation = models.CharField(max_length=10, null=True, blank=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    father_name = models.CharField(max_length=50, null=True, blank=True)
    birth_date = models.CharField(max_length=20, null=True, blank=True)
    genre = models.CharField(max_length=1, choices=GENRE_CHOICES, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    area = models.CharField(max_length=150, null=True, blank=True)
    city = models.CharField(max_length=15, null=True, blank=True)
    state = models.CharField(max_length=15, null=True, blank=True)
    country = models.CharField(max_length=15, null=True, blank=True)
    pincode = models.CharField(max_length=6, null=True, blank=True)
    phone = models.CharField(max_length=10,null=True, blank=True)
    email = models.CharField(max_length=150, null=True, blank=True)
    marital_status = models.CharField(max_length=1, choices=MARITAL_STATUS_CHOICES, null=True, blank=True)
    education = models.CharField(max_length=150, null=True, blank=True)
    education_detail = models.TextField(null=True, blank=True)
    occupation = models.CharField(max_length=150, null=True, blank=True)
    occupation_detail = models.TextField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False, auto_created=True)
    created = models.DateTimeField(auto_now=False, auto_now_add=True, auto_created=True)

    objects = SubprofileManager()

    def __str__(self):
        return str(self.first_name)

    def get_absolute_url(self):
        return self.user.profile.get_absolute_url()

    def get_update_url(self):
        return reverse("profile:subprofile_update", kwargs={"id": self.id})

    def get_delete_url(self):
        return reverse("profile:subprofile_delete", kwargs={"id": self.id})

    class Meta:
        ordering = ["id"]


class blog(models.Model):
    blog_title = models.CharField(max_length=255, null=True, blank=True)
    blog_text = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.blog_title)

    class Meta:
        ordering = ["-id"]


class ImageBlog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    imageblog_title = models.CharField(max_length=255, null=True, blank=True)
    mainimage = models.FileField(null=True, blank=True)
    status = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return str(self.imageblog_title)

    def get_absolute_url(self):
        return reverse("profile:imageblog_detail", kwargs={"id": self.id})

    def get_update_url(self):
        return reverse("profile:imageblog_update", kwargs={"id": self.id})

    def get_create_url(self):
        return reverse("profile:imageblog_detailcreate", kwargs={"id": self.id})


    class Meta:
        ordering = ["-id"]


class SubImageBlogManager(models.Manager):
    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(ImageBlog)
        obj_id = instance.id
        qs = super(SubImageBlogManager, self).filter(content_type=content_type, object_id=obj_id)
        return qs


class SubImageBlog(models.Model):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    extraimage = models.FileField(null=True, blank=True)
    status = models.IntegerField(null=True, blank=True)

    objects = SubImageBlogManager()

    class Meta:
        ordering = ["-id"]

templates/subprofile/detail.html
{% extends 'templates/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock %}
{% block bodyblock %}
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="#">
                <img src="{% static '/img/theme-logo.png' %}" alt="theme-logo" class="img-fluid">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile:profile_list' %}">directory <br/> યાદી</a>
                    </li>
                    <li class="nav-item  active">
                        <a class="nav-link" href="{{ user.profile.get_absolute_url }}">profile <br/> પ્રોફાઇલ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile:gallery' %}">photos <br/> ફોટા</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile:news' %}">news <br/> સમાચાર</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile:blog-view' %}">blog <br/> લેખ</a>
                    </li>
                </ul>
                <div class="account-btn">
                     <a href="{% url 'profile:logout' %}" class="btn" type="submit">sign out / સાઇન આઉટ કરો</a>
                </div>
            </div>
        </div>
    </nav>
    <section class="user-details">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="row">
                        <div class="col-sm-6 col-md-3 col-lg-2">
                            <p><b>Surname / અટક</b> : {{ item.last_name }}</p>
                        </div>
                        <div class="col-sm-6 col-md-3 col-lg-2">
                            <p><b>First Name / નામ</b> : {{ item.first_name }}</p>
                        </div>
                        <div class="col-sm-6 col-md-3 col-lg-2">
                            <p><b>Father's Name / પિતાનું નામ</b> : {{ item.father_name }}</p>
                        </div>
                        <div class="col-sm-6 col-md-3 col-lg-2">
                            <p><b>Date of Birth / જન્મતારીખ</b> : {{ item.birth_date }}</p>
                        </div>
                        <div class="col-sm-6 col-md-3 col-lg-2">
                            <p><b>Area / વિસ્તાર</b> : {{ item.area }}</p>
                        </div>
                        <div class="col-sm-6 col-md-3 col-lg-2">
                            <p><b>city/Town / શહેર</b> : {{ item.city }}</p>
                        </div>
                        <div class="col-sm-6 col-md-3 col-lg-2">
                            <p><b>State / રાજ્ય</b> : {{ item.state }}</p>
                        </div>
                        <div class="col-sm-6 col-md-3 col-lg-2">
                            <p><b>Phone no. / ફોન નંબર</b> : {{ item.phone }}</p>
                        </div>
                        <div class="col-sm-6 col-md-3 col-lg-2">
                            <p><b>Occupation / વ્યવસાય</b> : {{ item.occupation }}</p>
                        </div>
                        <div class="col-sm-6 col-md-3 col-lg-2">
                            <p><b>Occupation Detail / વ્યવસાયની વિગત</b> : {{ item.occupation_detail }}</p>
                        </div>
                        <div class="col-sm-6 col-md-3 col-lg-2">
                            <p><b>Education / શિક્ષણ</b> : {{ item.education }}</p>
                        </div>
                        <div class="col-sm-6 col-md-3 col-lg-2">
                            <p><b>Education Detail / શિક્ષણની વિગતો</b> : {{ item.education_detail }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="contact-info">
                    <h3 class="title">for help call</h3>
                    <ul>
                        <li>dilip lakhani : 9879140593</li>
                        <li>velji kachhadiya : 9712028988</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
{% endblock %}

templates/subprofile/update.html
{% extends 'templates/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    {{ title }}
{% endblock %}
{% load static %}
{% block bodyblock %}
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand" href="#">
                <img src="{% static '/img/theme-logo.png' %}" alt="theme-logo" class="img-fluid">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile:profile_list' %}">directory <br/> યાદી</a>
                    </li>
                    <li class="nav-item  active">
                        <a class="nav-link" href="{{ user.profile.get_absolute_url }}">profile <br/> પ્રોફાઇલ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile:gallery' %}">photos <br/> ફોટા</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile:news' %}">news <br/> સમાચાર</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile:blog-view' %}">blog <br/> લેખ</a>
                    </li>
                </ul>
                <div class="account-btn">
                    <a href="{% url 'profile:logout' %}" class="btn" type="submit">sign out / સાઇન આઉટ કરો</a>
                </div>
            </div>
        </div>
    </nav>
    <section class="update-deatils">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="title-wrapper text-center">
                        <h2 class="title">Update Profile</h2>
                    </div>
                </div>
                <form method="post" class="user-profile">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 col-lg-3">
                            <div id="div_id_first_name" class="form-group">
                                <label for="id_first_name" class="col-form-label ">First name / નામ</label>
                                <div class=""><input type="text" name="first_name" maxlength="50" class="textinput textInput form-control" id="id_first_name" {% if subprofile_form.first_name != None %}value="{{ subprofile_form.first_name }}"{% endif %}/></div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3">
                            <div id="div_id_last_name" class="form-group"><label for="id_last_name" class="col-form-label ">Surname / અટક </label>
                                <div class=""><input type="text" name="last_name" maxlength="50" class="textinput textInput form-control" id="id_last_name" {% if subprofile_form.last_name != None %}value="{{ subprofile_form.last_name }}"{% endif %}/></div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div id="div_id_father_name" class="form-group"><label for="id_father_name" class="col-form-label ">Father's name / પિતાનું નામ</label>
                                <div class=""><input type="text" name="father_name" maxlength="50" class="textinput textInput form-control" id="id_father_name" {% if subprofile_form.father_name != None %}value="{{ subprofile_form.father_name }}"{% endif %}/></div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3">
                            <div id="div_id_birth_date" class="input-group date"><label for="id_birth_date" class="col-form-label">
                                Birth date / જન્મતારીખ
                            </label>
                                <div class="" style="width: 100%;"><input type="text" name="birth_date" class="dateinput form-control" id="id_birth_date" data-provide="datepicker" {% if subprofile_form.birth_date != None %}value="{{ subprofile_form.birth_date }}"{% endif %}/></div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3">
                            <div id="div_id_genre" class="form-group"><label for="id_genre" class="col-form-label ">gender / જાતિ</label>
                                <div class=""><select name="genre" class="select form-control" id="id_genre">
                                        <option value="">---------</option>
                                        <option value="m">Male / પુરૂષ</option>
                                        <option value="f">Female / સ્ત્રી</option></select></div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div id="div_id_phone" class="form-group"><label for="id_phone" class="col-form-label ">Phone no./ ફોન નંબર</label>
                                <div class=""><input type="number" name="phone" value="7574962407" class="numberinput form-control" id="id_phone" {% if subprofile_form.phone.value != None %}value="{{ subprofile_form.phone.value }}" {% endif %}/></div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div id="div_id_address" class="form-group"><label for="id_address" class="col-form-label ">Address / સરનામું</label>
                                <div class=""><textarea name="address" cols="40" rows="5" maxlength="150" class="textarea form-control" id="id_address">{% if subprofile_form.address != None %}{{ subprofile_form.address }}{% endif %}</textarea></div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div id="div_id_area" class="form-group"><label for="id_area" class="col-form-label ">Area / વિસ્તાર</label>
                                <div class=""><input type="text" name="area" maxlength="150" class="textinput textInput form-control" id="id_area" {% if subprofile_form.area != None %}value="{{ subprofile_form.area }}" {% endif %}/></div>
                            </div>
                            <div id="div_id_city" class="form-group"><label for="id_city" class="col-form-label ">
                                City / શહેર
                            </label>
                                <div class=""><input type="text" name="city" maxlength="15" class="textinput textInput form-control" id="id_city" {% if subprofile_form.city != None %}value="{{ subprofile_form.city }}" {% endif %}/></div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3">
                            <div id="div_id_state" class="form-group"><label for="id_state" class="col-form-label ">State / રાજ્ય</label>
                                <div class=""><input type="text" name="state" maxlength="15" class="textinput textInput form-control" id="id_state" {% if subprofile_form.state != None %}value="{{ subprofile_form.state }}" {% endif %}/></div>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-3">
                            <div id="div_id_pincode" class="form-group"><label for="id_pincode" class="col-form-label ">Pincode / પીન કોડ</label>
                                <div class=""><input type="number" name="pincode" min="0" class="numberinput form-control" id="id_pincode" {% if subprofile_form.pincode != None %}value="{{ subprofile_form.pincode }}" {% endif %}/></div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div id="div_id_country" class="form-group"><label for="id_country" class="col-form-label ">Country / દેશ</label>
                                <div class=""><input type="text" name="country" maxlength="15" class="textinput textInput form-control" id="id_country"{% if subprofile_form.country != None %} value="{{ subprofile_form.country }}" {% endif %}/></div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div id="div_id_email" class="form-group"><label for="id_email" class="col-form-label ">Email / ઇમેઇલ</label>
                                <div class=""><input type="text" name="email" maxlength="150" class="textinput textInput form-control" id="id_email"{% if subprofile_form.email != None %} value="{{ subprofile_form.email }}" {% endif %}/></div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div id="div_id_marital_status" class="form-group"><label for="id_marital_status" class="col-form-label ">Marital status / વૈવાહિક સ્થિતિ</label>
                                <div class=""><select name="marital_status" class="select form-control" id="id_marital_status"}>
                                    <option value="">---------</option>
                                    <option value="s">Single / અપરિણિત</option>
                                    <option value="m">married / વિવાહિત</option>
                                    <option value="d">Divorced / છૂટાછેડા લીધા</option>
                                    <option value="w">Widowed / વિધવા</option></select></div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div id="div_id_education" class="form-group"><label for="id_education" class="col-form-label ">Education / શિક્ષણ</label>
                                <div class=""><input type="text" name="education" maxlength="150" class="textinput textInput form-control" id="id_education"{% if subprofile_form.education != None %} value="{{ subprofile_form.education }}" {% endif %}/></div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div id="div_id_occupation" class="form-group"><label for="id_occupation" class="col-form-label ">Occupation / વ્યવસાય</label>
                                <div class=""><input type="text" name="occupation" maxlength="150" class="textinput textInput form-control" id="id_occupation"{% if subprofile_form.occupation != None %} value="{{ subprofile_form.occupation }}" {% endif %}/></div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div id="div_id_education_detail" class="form-group"><label for="id_education_detail" class="col-form-label ">Education detail / શિક્ષણની વિગતો</label>
                                <div class=""><textarea name="education_detail" cols="40" rows="5" class="textarea form-control" id="id_education_detail">{% if subprofile_form.education_detail != None %}{{ subprofile_form.education_detail }}{% endif %}</textarea></div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div id="div_id_occupation_detail" class="form-group"><label for="id_occupation_detail" class="col-form-label ">Occupation detail / વ્યવસાયની વિગત</label>
                                <div class=""><textarea name="occupation_detail" cols="40" rows="5" class="textarea form-control" id="id_occupation_detail">{% if subprofile_form.occupation_detail != None %}{{ subprofile_form.occupation_detail }}{% endif %}</textarea></div>
                            </div>
                        </div>
                    </div>
                    <div class="submit-btn text-right">
                        <button type="submit" class="btn">save / સાચવો</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
<script>
 $("#id_genre").val('{{ subprofile_form.genre }}');
 $("#id_marital_status").val('{{ subprofile_form.marital_status }}');
</script>
{% endblock %}